services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '8888:8888'  # Prometheus metrics endpoint
      - '8889:8889'  # Prometheus exporter endpoint (if needed)
      - '4317:4317'  # OTLP gRPC receiver
      - '4318:4318'  # OTLP HTTP receiver
    depends_on:
      - nginx-exporter

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command:
      - '--nginx.scrape-uri=http://nginx:80/stub_status'
    ports:
      - '9113:9113'
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - collector

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

